# Global settings
namespace: innerlink


registry:
  #For airgapped deployments
  base_url: "localhost:5000"
  busy_box_url: "localhost:5000"
  postgres_url: "localhost:5000"
  url: "localhost:5000/ghcr.io/innerlink-ai"
  huggingface_url: "localhost:5000/ghcr.io/huggingface"

istio:
  enabled: true
  gateway:
    name: innerlink-gw
    port: 8080          # keep 8080 (already works) or change to 80 + hostNetwork
  hosts:
    - "*"               # wildcard is OK when AuthZ is in place
  mTlsMode: STRICT      # mesh‑internal
  authzAllowAll: true   # initial open policy; tighten later



tgi:
  args:
    maxBatchPrefillTokens: 16384
  model:
    #id: "Qwen/QwQ-32B"
    #id: "deepseek-ai/DeepSeek-R1-Distill-Qwen-32B"  
    path: "/data/model_weights/deepseek-ai/DeepSeek-R1-Distill-Qwen-32B"
    offline: "1"
  gpu:
    tensorParallelSize: "4"
    cudaVisibleDevices: "0,1,2,3"

# PostgreSQL Configuration
postgres:
  ssl:
    # Certificate will be read directly from local filesystem
    certPath: "/etc/postgresql/ssl/postgres-certs"
