# Global settings
namespace: innerlink

# Istio Configuration

istio:
  enabled: true
  gateway:
    name: innerlink-gw
    port: 8080          # keep 8080 (already works) or change to 80 + hostNetwork
  hosts:
    - "*"               # wildcard is OK when AuthZ is in place
  mTlsMode: STRICT      # mesh‑internal
  authzAllowAll: true   # initial open policy; tighten later



# Image Registry Credentials
imageCredentials:
  dockerconfig: "eyJhdXRocyI6eyJnaGNyLmlvIjp7InVzZXJuYW1lIjoibWF0dGdvcmIiLCJwYXNzd29yZCI6ImdocF9TNExrZzcxOEZkZ0NlaGFhRmpuSkFJZEFwMlM3VmwzaTRnRUciLCJhdXRoIjoiYldGMGRHZHZjbUk2WjJod1gxTTBUR3RuTnpFNFJtUm5RMlZvWVdGR2FtNUtRVWxrUVhBeVV6ZFdiRE5wTkdkRlJ3PT0ifX19"
  
registry:
  url: "ghcr.io/innerlink-ai"
  huggingface_url: "ghcr.io/huggingface"

# TGI Configuration
tgi:
  args:
    maxBatchPrefillTokens: 1024
  model:
    path: "/data/model_weights/meta-llama/Llama-2-7b-chat-hf"
    offline: "0"

# PostgreSQL Configuration
postgres:
  ssl:
    # Certificate will be read directly from local filesystem
    certPath: "/etc/postgresql/ssl/postgres-certs"
