{{- if .Values.backend.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: {{ .Values.namespace }} 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      {{- if and (hasKey .Values "imageCredentials") (hasKey .Values.imageCredentials "dockerconfig") }}
      imagePullSecrets:
      - name: ghcr-secret
      {{- end }}
      containers:
      - name: backend
        image: "{{ .Values.registry.url }}/innerlink-backend:latest"
        command: ["./scripts/start-script.sh"]
        args: ["postgres", "5432", "--", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
        ports:
        - containerPort: 8000
        env:
        - name: TGI_URL
          value: "http://tgi:8080"
        - name: DATABASE_URL
          value: "postgresql://admin:SuperSecurePassword@postgres:5432/postgres"
        - name: DOMAIN
          value: "localhost:8080"
        - name: HF_HUB_OFFLINE
          value: "{{ .Values.tgi.model.offline }}"
        - name: ADMIN_DATABASE_URL
          value: "postgresql://admin:SuperSecurePassword@postgres:5432/admin_db"
        - name: CHAT_DATABASE_URL
          value: "postgresql://admin:SuperSecurePassword@postgres:5432/chat_db"
        - name: COLLECTIONS_DATABASE_URL
          value: "postgresql://admin:SuperSecurePassword@postgres:5432/collections_db"
        - name: REDIS_URL
          value: "redis://redis:6379/0"
        - name: DATA_DIR
          value: "/app/data"
        - name: LOG_LEVEL
          value: "DEBUG"
        - name: USE_CPU
          value: "false"
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: jwt-secret
              key: JWT_SECRET
      
        volumeMounts:
        - name: app-data
          mountPath: /app/data
        #- name: model-weights-cache
         # mountPath: /app/data/model_weights
      volumes:
      - name: app-data
        persistentVolumeClaim:
          claimName: data-pvc
      #- name: model-weights-cache
       # persistentVolumeClaim:
        #  claimName: model-weights-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: backend
  ports:
  - name: http           # <-- critical: starts with “http”
    port: 8000           # port exposed inside the cluster
    targetPort: 8000     # containerPort in the Pod
  type: ClusterIP
{{- end }}