apiVersion: batch/v1
kind: Job
metadata:
  name: storage-directory-creator
  namespace: {{ .Values.namespace }}
  annotations:
    sidecar.istio.io/inject: "false"   # <- disable Istio sidecar injection
spec:
  ttlSecondsAfterFinished: 30  # <- Job will auto-delete itself 30 seconds after success or failure
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"  # <- ALSO needed inside the pod template!
    spec:
      restartPolicy: OnFailure
      containers:
      - name: directory-creator
        image: "{{ .Values.registry.busy_box_url }}/busybox:latest"
        command:
        - sh
        - -c
        - |
          mkdir -p /host/app/data/postgres
          mkdir -p /host/app/data/redis
          mkdir -p /host/app/data/model_weights
          mkdir -p /host/app/data/document_storage
          mkdir -p /host/app/data/data
          chmod -R 777 /host/app/data
          echo "All directories created successfully"
        volumeMounts:
        - name: host-root
          mountPath: /host
        securityContext:
          privileged: true
      volumes:
      - name: host-root
        hostPath:
          path: /