apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: storage-directory-creator
  namespace: {{ .Values.namespace }} 
spec:
  selector:
    matchLabels:
      app: storage-directory-creator
  template:
    metadata:
      labels:
        app: storage-directory-creator
    spec:
      initContainers:
      - name: directory-creator
        image: "{{ .Values.registry.url }}/busybox"
        command:
        - sh
        - -c
        - |
          mkdir -p /host/app/data/postgres
          mkdir -p /host/app/data/redis
          mkdir -p /host/app/data/model_weights
          mkdir -p /host/app/data/document_storage
          mkdir -p /host/app/data/data
          chmod -R 777 /host/app/data
          echo "All directories created successfully"
        volumeMounts:
        - name: host-root
          mountPath: /host
        securityContext:
          privileged: true  # Needed to create directories on host
      containers:
      - name: pause
        image: gcr.io/google_containers/pause:3.2
        resources:
          limits:
            cpu: 100m
            memory: 30Mi
          requests:
            cpu: 10m
            memory: 10Mi
      volumes:
      - name: host-root
        hostPath:
          path: /
      terminationGracePeriodSeconds: 5