apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: innerlink-ingress
  namespace: {{ .Values.namespace }} 
spec:
  rules:
  #- host: demo.innerlink.ai
  - http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: backend
            port:
              number: 8000
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              number: 80