apiVersion: v1
kind: PersistentVolume
metadata:
  name: model-weights-pv
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete # Or Retain, depending on your needs.
  storageClassName: local-storage
  local:
    #path: /app/data/model_weights # The directory on your host node.
    path: /opt/dlami/nvme/model_weights
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: role
          operator: In
          values:
          - storage
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: model-weights-pvc
  namespace: {{ .Values.namespace }} 
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: local-storage # Match the PersistentVolume's storageClassName
