apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-ssl-config
  namespace: {{ .Values.namespace }}
data:
  postgresql.conf: |-
    # SSL Configuration
    ssl = on
    ssl_cert_file = '/etc/postgresql/ssl/postgres-certs/server.crt'
    ssl_key_file = '/etc/postgresql/ssl/postgres-certs/server.key'
    # Require SSL for all connections
    ssl_prefer_server_ciphers = on
    ssl_min_protocol_version = 'TLSv1.2' 