{{- if hasKey .Values "imageCredentials" }}
{{- if hasKey .Values.imageCredentials "dockerconfig" }}
apiVersion: v1
kind: Secret
metadata:
  name: ghcr-secret
  namespace: {{ .Values.namespace }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.imageCredentials.dockerconfig | quote }}
{{- end }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-ssl-certs
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  server.crt: {{ .Files.Get "certs/server.crt" | b64enc | quote }}
  server.key: {{ .Files.Get "certs/server.key" | b64enc | quote }}