apiVersion: apps/v1
kind: Deployment
metadata:
  name: tgi
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tgi
  template:
    metadata:
      labels:
        app: tgi
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
      runtimeClassName: nvidia
      containers:
      - name: tgi
        image: "{{ .Values.registry.huggingface_url }}/text-generation-inference:2.4.1"
        args:
        - "--max-batch-prefill-tokens"
        - "{{ .Values.tgi.args.maxBatchPrefillTokens }}"
        #resources:
          #limits:
            #nvidia.com/gpu: 1
        ports:
        - containerPort: 8080
        env:
        - name: MODEL_ID
          value: "{{ .Values.tgi.model.path }}"
        - name: HF_HUB_OFFLINE
          value: "{{ .Values.tgi.model.offline }}"
        - name: TENSOR_PARALLEL_SIZE
          value: "{{ .Values.tgi.gpu.tensorParallelSize }}"
        - name: CUDA_VISIBLE_DEVICES
          value: "{{ .Values.tgi.gpu.cudaVisibleDevices }}"
        - name: HOST
          value: "0.0.0.0"
        - name: PORT
          value: "8080"
       # - name: HUGGING_FACE_HUB_CACHE
          #value: "/data/"
        - name: DTYPE
          value: "float16"
        - name: NUMBA_CACHE_DIR # Add this line
          value: "/data/.cache/numba"
        - name: OUTLINES_CACHE_DIR
          value: "/data/.cache/outlines"
        - name: TRANSFORMERS_CACHE
          value: "/data/.cache/huggingface"
        - name: TRITON_CACHE_DIR
          value: "/data/.cache/triton"
        - name: TRANSFORMERS_CACHE
          value: "/data/.cache/huggingface"
        - name: XDG_CACHE_HOME
          value: "/data/.cache"
          
        - name: MAX_TOTAL_TOKENS
          value: "2056"
        - name: MAX_INPUT_LENGTH
          value: "1024"  # Limit input to 512
        - name: MAX_BATCH_PREFILL_TOKENS
          value: "2056"
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
          readOnlyRootFilesystem: false
        volumeMounts:
        - name: model-weights-storage
          mountPath: /data
      volumes:
      - name: model-weights-storage
        persistentVolumeClaim:
          claimName: model-weights-pvc
